name: Alteron
version: 0.1
main: zerrium.Alteron
api-version: 1.13
author: zerrium
commands:
  alteron:
    description: See your advancement progress details
    usage: /alteron
    permission: Alteron.use